pipeline{
    agent any
    stages{
        stage("checkout Code"){
            steps{
                git url: "https://github.com/YannickGongue/WebAppI.git",
                    branch: "main"
            }
        }
        stage("Check :net Version"){
            steps{
                sh "dotnet --version"
        }
        stage ("Build"){
            steps{
                sh "dotnet build WebAppI.sln -c Release"
            }
        }
    }
      post {
        success {
            echo "✅ Pipeline SUCCESS"
        }
        failure {
            echo "❌ Pipeline FAILED"
        }
    }
}